### ISSUE TITLE
What argument does insert method accept?

### ISSUE THREAD

**Issue by mlewis-everley** [mkloubert/nativescript-bitmap-factory#5]
Apologies if this is in the wrong place, if it is, where is the best place to post this question?

I am trying to rescale a bitmap image. As far as I can tell the process should involve:

1. Create a BitmapFactory instance that is the original image size.
2. Insert the image into the BitmapFactory canvas.
3. Use the resize (or resizeWidth/resizeHeight) function to scale the image.
4 Convert the image to an imagesource and save.

My code for doing this is:

````
        var image = ImageSource.fromFile(file_path);
        var bmp = BitmapFactory.create(width, height);

        bmp.dispose(function(b) {
            // Causes an out of memory exception
            b.insert(image.toBase64String(Enums.ImageFormat.jpeg));

            // Causes a "Not valid bitmap" exception.
            //b.insert(image);

            // Tried on android, Causes a "Not valid bitmap" exception.
            //b.insert(image.android);

            // Causes a "Not valid bitmap" exception.
            //b.insert(file_path);

            var b2 = b.resize({
                width: thumb_width,
                height: thumb_height
            });

            var thumb_image = b2.toImageSource();

            thumb_image.saveToFile(
                temp_thumb_path,
                Enums.ImageFormat.jpeg
            );
        });
````

I have tried to use the insert function in several ways, but loading from a base64 string results in an out of memory exception.

I have also tried passing an imagesource object, a native object or a file path and all cause a "Not valid bitmap" exception.

Is this correct? Can I only insert from a base64 string? Or am i using this incorrectly?

Any help greatly appreciated...

**Comment by mkloubert** [comment]
Yes, you tried it the right way, but I forgot to implement it!

[I released version 1.4.1](https://www.npmjs.com/package/nativescript-bitmap-factory) that is now able to use the following kind of objects:

* Base64 strings (the way you tried, but as you see: it needs a lot of memory and time)
* [ImageSources](https://docs.nativescript.org/cookbook/image-source) (it reads the underlying native object automatically)
* native objects like [Bitmap](https://developer.android.com/reference/android/graphics/Bitmap.html) or [UIImage](https://developer.apple.com/reference/uikit/uiimage)

**Comment by mlewis-everley** [comment]
Hi Mkloubert,

No probs, thanks for the quick update.

I have updated to 1.4.1, but now I get the following error (both for ImageSource and android Bitmap object):

Error: java.lang.IllegalStateException: Immutable bitmap passed to Canvas constructor

Stack trace is:

````
    android.graphics.Canvas.<init>(Canvas.java:142)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
    com.tns.Runtime.callJSMethod(Runtime.java:716)
    com.tns.Runtime.callJSMethod(Runtime.java:697)
    com.tns.Runtime.callJSMethod(Runtime.java:687)
    com.tns.gen.java.lang.Runnable.run(java.lang.Runnable.java)
    android.os.Handler.handleCallback(Handler.java:739)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:234)
    android.app.ActivityThread.main(ActivityThread.java:5526)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
````

According to Stack Overflow, the working bitmap needs to be converted to a mutable bitmap on android (not tested on iOS yet).

I have tried to change: https://github.com/mkloubert/nativescript-bitmap-factory/blob/master/plugin/BitmapFactory.android.js#L43

To something like:

````
    this._isDisposed = false;
    this._nativeObject = bitmap;
    this._options = opts;
    var mutable = bitmap.copy(android.graphics.Bitmap.Config.ARGB_8888, true);
    this._c = new android.graphics.Canvas(mutable);
````

However this again causes an out of memory exception.

There is some more info [here](http://stackoverflow.com/questions/4349075/bitmapfactory-decoderesource-returns-a-mutable-bitmap-in-android-2-2-and-an-immu/9194259#9194259) on a solution with minimal memory implications but to be honest this is a bit beyond me :-s.

Any ideas?

**Comment by mlewis-everley** [comment]
Managed to test insert (and resize) on iOS and it works like a dream :-)

**Comment by mkloubert** [comment]
@iOS: 👍 

@Android:

Thanks for the code examples! :-)

I used them to **release version 1.5.0** with a new helper function that should be fix the memory leaks:

The function is called **makeMutable()**. It works on Android and iOS.

```javascript
var BitmapFactory = require('nativescript-bitmap-factory');

// this can be:
// 
// * a native object like Bitmap or UIImage
// * an IBitmap
// * an ImageSource
var nativeObj;

var mutable = BitmapFactory.makeMutable(nativeObj);
```

By default this will clone the _nativeObj_ in memory, but you can define a "stradegy" to clone it by submitting custom options that have the following interface:

```typescript
/**
 * Options for 'makeMutable()' functon.
 */
export interface IMakeMutableOptions {
    /**
     * Dispose current bitmap or not.
     *
     * Default: (false)
     */
    disposeCurrent?: boolean;
    /**
     * Options for handling temp data / files.
     */
    temp?: {
        /**
         * This is only used if stradegy is 'Custom' and
         * is used to define the custom temp directory.
         *
         * This can be a string or a native object that represents a file
         * like java.lang.File on Android.
         */
        directory?: any;
        /**
         * The stradegy.
         *
         * Default: Memory
         */
        stradegy?: TempFileStradegy;
    };
}
```

The **disposeCurrent** property means it will recycle / dispose the submitted image after a "clone" has been created successfully. This is _(false)_ by default and should only be set to _(true)_ if you do not need the original image anymore.

In the **temp** section you can define the **stradegy** property:

```typescript
/**
 * List of temp file stradegies.
 */
export declare enum TempFileStradegy {
    /**
     * Memory
     */
    Memory = 1,
    /**
     * Cache directory
     */
    CacheDir = 2,
    /**
     * External directory
     */
    ExternalCacheDir = 3,
    /**
     * Custom directory
     */
    Custom = 4,
}
```

You can choose beetween:

- **Memory**: Clone in memory (default)
- **CacheDir**: Saves the cloned image to a temporary file that is stored in [cache directory](https://developer.android.com/reference/android/content/Context.html#getCacheDir()) (Android only); this version should NOT need additional permissions, bebause files are stored inside the app directory
- **ExternalCacheDir**: Saves the cloned image to a temporary file that is stored in [EXTERNAL cache directory](https://developer.android.com/reference/android/content/Context.html#getExternalCacheDir()) (Android only); this may require additional [WRITE_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission.html#WRITE_EXTERNAL_STORAGE) permissions
- **Custom**: You also can use a custom directory (path) what is defined in the **temp.directory** property in the options object (Android only); Default: Cache directory.

_"Android only"_ means: Also works on iOS, but has no effect, because currently anything is cloned in memory there.

Example:

```typescript
import BitmapFactory = require('nativescript-bitmap-factory');

// your "native" image object
let nativeObj: any;

let opts: BitmapFactory.IMakeMutableOptions = {
    disposeCurrent: true,

    temp: {
        stradegy: BitmapFactory.TempFileStradegy.CacheDir,
    }
};

let mutable = BitmapFactory.makeMutable(nativeObj, opts);
```

**Comment by mlewis-everley** [comment]
Just letting you know, these seems to be working as expected on iOS and Android, cheers for the help :-)
